apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clipdrop-data
  namespace: clips
  labels:
    app: clipdrop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
