apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/managed-by: argocd

resources:
  # Monitoring
  - manifests/monitoring/namespace.yaml
  - manifests/monitoring/node-exporter.yaml
  
  # Heimdall
  - manifests/heimdall/namespace.yaml
  - manifests/heimdall/deployment.yaml
  
  # Vaultwarden
  - manifests/vaultwarden/namespace.yaml
  - manifests/vaultwarden/deployment.yaml
  
  # Code Server
  - manifests/code-server/namespace.yaml
  - manifests/code-server/deployment.yaml
  
  # Grafana
  - manifests/grafana/namespace.yaml
  - manifests/grafana/deployment.yaml
  
  # Prometheus
  - manifests/prometheus/namespace.yaml
  - manifests/prometheus/configmap.yaml
  - manifests/prometheus/deployment.yaml
  
  # Portainer (Storage Monitoring)
  - manifests/portainer/namespace.yaml
  - manifests/portainer/deployment.yaml