apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chill-pasture-data
  namespace: chill-farm
  labels:
    app: chill-pasture
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
