apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: joplin-tls
  namespace: joplin
spec:
  secretName: joplin-tls
  duration: 2160h0m0s # 90d
  renewBefore: 720h0m0s # 30d
  dnsNames:
  - joplin.racktocloud.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  # EXPLICITLY USE DNS01 WITH CLOUDFLARE
  usages:
  - digital signature
  - key encipherment