apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-server
  namespace: joplin
  labels:
    app: joplin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-server
  template:
    metadata:
      labels:
        app: joplin-server
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "joplin"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/joplin/database"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/joplin/database" -}}
          export POSTGRES_HOST="{{ .Data.data.postgres_host }}"
          export POSTGRES_PORT="{{ .Data.data.postgres_port }}"
          export POSTGRES_USER="{{ .Data.data.postgres_user }}"
          export POSTGRES_PASSWORD="{{ .Data.data.postgres_password }}"
          export POSTGRES_DATABASE="{{ .Data.data.database_name }}"
          {{- end }}
    spec:
      serviceAccountName: joplin
      containers:
      - name: joplin-server
        image: joplin/server:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: [". /vault/secrets/db && exec tini -- yarn start-prod"]
        ports:
        - name: http
          containerPort: 22300
          protocol: TCP
        env:
        - name: APP_BASE_URL
          value: "https://joplin.racktocloud.com"
        - name: DB_CLIENT
          value: "pg"
        - name: TRUSTED_DOMAINS
          value: "localhost,127.0.0.1,joplin.racktocloud.com,joplin-server,joplin-server.joplin,joplin-server.joplin.svc.cluster.local,10.0.0.0/8"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"