apiVersion: v1
kind: ServiceAccount
metadata:
  name: joplin
  namespace: joplin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: joplin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joplin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: joplin
subjects:
- kind: ServiceAccount
  name: joplin
  namespace: joplin