apiVersion: v1
kind: Secret
metadata:
  name: joplin-db
  namespace: joplin
type: Opaque
stringData:
  postgres_host: "postgresql.databases.svc.cluster.local"
  postgres_port: "5432"
  postgres_user: "joplin"
  postgres_password: "JoplinDB@Secure123"
  postgres_database: "joplin"