apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        container.apparmor.security.beta.kubernetes.io/node-exporter: unconfined
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      securityContext:
        runAsUser: 0
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9100
          hostPort: 9100
        args:
          - '--path.rootfs=/rootfs'
          - '--path.procfs=/proc'
          - '--path.sysfs=/sys'
          - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: procfs
          mountPath: /proc
          readOnly: true
        - name: sysfs
          mountPath: /sys
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: procfs
        hostPath:
          path: /proc
      - name: sysfs
        hostPath:
          path: /sys