apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: default
data:
  vault-agent-config.hcl: |
    vault {
      address = "http://vault.vault.svc.cluster.local:8200"
    }
    
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "default-role"
        }
      }
      
      sink "file" {
        config = {
          path = "/vault/secrets/.vault-token"
        }
      }
    }
    
    cache {
      use_auto_auth_token = true
    }
    
    listener "unix" {
      address = "/vault/secrets/vault.sock"
      tls_disable = true
    }